"""Base strategy class and shared data types for the backtesting engine."""

from __future__ import annotations

import datetime as dt
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class Signal:
    """A trade entry signal generated by a strategy."""

    date: dt.date
    time: Optional[dt.time]  # None for daily-only strategies
    ticker: str
    direction: str  # "long" or "short"
    entry_price: float
    stop_price: float
    target_price: Optional[float] = None  # None = no fixed target (e.g. EOD exit)
    quality_score: str = ""  # strategy-specific quality flags (e.g. "TMB")
    quality_flags: dict = field(default_factory=dict)  # breakdown of quality components
    metadata: dict = field(default_factory=dict)  # strategy-specific extra data


@dataclass
class Exit:
    """An exit decision returned by a strategy's check_exit method."""

    should_exit: bool
    exit_price: float
    reason: str  # "ko", "stop", "target", "close", "max_hold", "stack_break"
    metadata: dict = field(default_factory=dict)


@dataclass
class Trade:
    """A completed trade with full P&L and regime data."""

    # Identity
    ticker: str
    date: dt.date
    strategy: str

    # Entry/exit
    direction: str
    entry_price: float
    exit_price: float
    stop_price: float
    target_price: Optional[float]
    entry_time: Optional[dt.time] = None
    exit_time: Optional[str] = None

    # Results
    pnl: float = 0.0  # SEK P&L (leveraged product)
    pnl_pct: float = 0.0  # underlying price change %
    outcome: str = ""  # "ko", "stop", "target", "close", "max_hold", "stack_break"
    days_held: int = 1

    # Quality
    quality_score: str = ""
    quality_flags: dict = field(default_factory=dict)

    # Regime (filled in by BacktestEngine from regime_history)
    regime_composite: str = ""
    regime_volatility: str = ""
    regime_cycle: str = ""
    regime_risk: str = ""
    regime_monetary: str = ""

    # Extra
    metadata: dict = field(default_factory=dict)


class BaseStrategy(ABC):
    """Abstract base class for all backtesting strategies.

    Subclasses must implement:
      - generate_signals(data, date) -> list[Signal]
      - check_exit(trade_signal, current_bar, bars_since_entry) -> Optional[Exit]

    Class attributes:
      - name: human-readable strategy name
      - requires_intraday: True if the strategy needs 5-min bars, False for daily
    """

    name: str = "BaseStrategy"
    requires_intraday: bool = False

    @abstractmethod
    def generate_signals(self, data: dict, date: dt.date) -> list[Signal]:
        """Generate entry signals for a given date.

        Args:
            data: dict with keys depending on strategy requirements:
                - "intraday": DataFrame of 5-min OHLCV bars for the ticker
                - "daily": DataFrame of daily OHLCV bars for the ticker
                - "ticker": str ticker symbol
            date: the trading date to generate signals for

        Returns:
            List of Signal objects (may be empty).
        """

    @abstractmethod
    def check_exit(
        self,
        signal: Signal,
        current_bar: dict,
        bars_since_entry: int,
        day_index: int,
    ) -> Optional[Exit]:
        """Check whether an active trade should exit on the current bar.

        Args:
            signal: the original Signal that opened this trade
            current_bar: dict with Open, High, Low, Close, Volume keys
            bars_since_entry: number of bars elapsed since entry
            day_index: number of trading days elapsed since entry (0 = entry day)

        Returns:
            Exit object if trade should close, None to keep holding.
        """
